name: airbnb_lakehouse
version: "1.0.0"
config-version: 2

profile: airbnb_trino

model-paths: ["models"]
test-paths:  ["tests"]
docs-paths:  ["docs"]

models:
  airbnb_lakehouse:
    staging:
      +materialized: view          # staging = views nhẹ, không tốn storage
      +schema: silver
    marts:
      +materialized: table         # marts = Iceberg tables thật sự
      +schema: gold
